#!/usr/bin/env bash

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

usage() {
    printf "Usage: %s COMMAND\n" "$0" >&2
    printf "Available commands:\n" >&2
    printf -- "- container\n" >&2
    printf -- "- test\n" >&2
    printf -- "- release\n" >&2
    exit 1
}

release() {
    if ! git diff-index --quiet HEAD --; then
        printf "Working directory not clean. Aborting release\n" >&2
        exit 1
    fi

    set -ev

    rm -rf dist build
    python setup.py bdist_wheel --universal
    twine upload dist/*

    local version
    version=v"$(python setup.py --version)"
    git push --tags origin master
    hub release create -m "$version" -e "$version"
}

main() {
    case "$1" in
        test )
            docker run -it --rm -e BITBUCKET_REST_API_AUTH="$BITBUCKET_REST_API_AUTH" -v "$ROOT_DIR":/opt/bibu -w /opt/bibu pylipp/bibu:latest bats -r tests
            ;;
        container )
            docker run -it --rm -e BITBUCKET_REST_API_AUTH="$BITBUCKET_REST_API_AUTH" -v "$ROOT_DIR":/opt/bibu -w /opt/bibu pylipp/bibu:latest
            ;;
        release )
            release
            ;;
        * )
            usage
            ;;
    esac
}

main "$@"
