#!/usr/bin/env bash

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

usage() {
    printf "Usage: %s COMMAND\n" "$0" >&2
    printf "Available commands:\n" >&2
    printf -- "- container\n" >&2
    printf -- "- test\n" >&2
    exit 1
}

main() {
    case "$1" in
        test )
            docker run -it --rm -e BITBUCKET_REST_API_AUTH="$BITBUCKET_REST_API_AUTH" -v "$ROOT_DIR":/opt/bibu -w /opt/bibu pylipp/bibu:latest bats -r tests
            ;;
        container )
            docker run -it --rm -e BITBUCKET_REST_API_AUTH="$BITBUCKET_REST_API_AUTH" -v "$ROOT_DIR":/opt/bibu -w /opt/bibu pylipp/bibu:latest
            ;;
        * )
            usage
            ;;
    esac
}

main "$@"
